SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT* FROM producto;
SELECT nombre AS nom_de_producto, precio AS euros, 1.065*precio AS dollars FROM producto;
SELECT nombre AS nom_de_producto, precio AS euros, 1.065*precio AS dollars FROM producto;
SELECT ucase(nombre), precio FROM producto;
SELECT lcase(nombre), precio FROM producto;
SELECT nombre, ucase(LEFT(nombre,2)) FROM fabricante;
SELECT nombre, round(precio) FROM producto;
SELECT nombre, truncate(precio, 0) FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT DISTINCT codigo_fabricante FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre FROM producto ORDER BY nombre ASC, precio DESC;
SELECT* FROM fabricante LIMIT 5;
SELECT* FROM fabricante LIMIT 3,2;
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = '2';
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo;
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo ORDER BY f.nombre ASC;
SELECT p.codigo, p.nombre, p.codigo_fabricante, f.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo ORDER BY p.codigo ASC;
SELECT p.nombre, p.precio, f.nombre AS fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo ORDER BY p.precio ASC LIMIT 1;
SELECT p.nombre, p.precio, f.nombre AS fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo ORDER BY p.precio DESC LIMIT 1;
SELECT * FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre = 'lenovo';
SELECT * FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre = 'crucial'AND p.precio > 200;
SELECT * FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre = 'asus' OR f.nombre = 'hewlett-packard' OR f.nombre = 'seagate';
SELECT * FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre IN( 'asus' , 'hewlett-packard' , 'seagate');
SELECT p.nombre, p.precio FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre LIKE "%e";
SELECT p.nombre, p.precio FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre REGEXP 'w';
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE p.precio >=180 ORDER BY p.precio DESC, p.nombre ASC;
SELECT DISTINCT f.codigo, f.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo;
SELECT* FROM fabricante f LEFT JOIN producto p ON f.codigo=p.codigo_fabricante;
SELECT* FROM fabricante f LEFT JOIN producto p ON f.codigo=p.codigo_fabricante WHERE p.nombre IS NULL;
SELECT p.nombre, p.precio FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre = 'lenovo';
SELECT * FROM producto p WHERE p.precio = (SELECT MAX(p.precio) FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre LIKE 'lenovo');
SELECT p.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre LIKE 'lenovo' AND p.precio = (SELECT MAX(p.precio) FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre LIKE 'lenovo');
SELECT p.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre LIKE 'hewlett-packard' AND p.precio = (SELECT MIN(p.precio) FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre LIKE 'hewlett-packard');
SELECT * FROM producto p WHERE p.precio >= (SELECT MAX(p.precio) FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre LIKE 'lenovo');
SELECT * FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre LIKE 'asus' AND p.precio > (SELECT AVG(p.precio) FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre LIKE 'asus');